<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Version>1.6.0</Version>
    <AssemblyVersion>1.6.0.0</AssemblyVersion>
    <FileVersion>1.6.0.0</FileVersion>
    <Product>ProtoHydra</Product>
  </PropertyGroup>
</Project>

